language: python
python: "2.7"
notifications:
  slack: bdlssawesome:h3cSZobT2OWduthPX18y9eLk
before_install:
install:
- sudo apt-get install $(cat ubuntu_requirements)
- pip install zc.buildout
- buildout init
- bin/buildout -N -t 3 -c travis.cfg
script:
- nosetests -v --with-coverage --cover-tests --cover-package=nosebasictests nosebasictests/tests.py